name: cyber_glass_app
description: "A mobile application for CyberGlass."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.0

  # Data models (code generation)
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Bluetooth
  flutter_blue_plus: ^1.31.0
  permission_handler: ^11.0.0

  # Storage
  shared_preferences: ^2.2.2

  # Routing
  go_router: ^12.1.0

  # Service Providers
  web_socket_channel: ^3.0.3
  sound_stream: ^0.4.2
  record: ^6.1.2
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
